# Generated by Django 5.0.1 on 2024-01-24 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotesapp.author')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotesapp.quote')),
            ],
        ),
    ]
