# Generated by Django 5.0.1 on 2024-01-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_authorquote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorQuote',
        ),
    ]
